In [2]:
!nvidia-smi

Sun Apr 10 14:45:45 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 512.15       Driver Version: 512.15       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   50C    P8    12W /  N/A |    240MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [6]:
import torch
from torch import nn
from d2l import torch as d2l

torch.device('cpu'),torch.cuda.device('cuda')

(device(type='cpu'), <torch.cuda.device at 0x21261f351c0>)

In [4]:
torch.cuda.device_count()

1

In [9]:
# 定义调用GPU
def try_gpu(i=0):  #@save
    """如果存往，则返回gPu(i),否则返回cpu()。"""
    if torch.cuda.device_count()>=i+1:
        return torch.device(f'cuda:{i}')
    return torch.device('cpu')

def try_all_gpus():   #@save
    "返回所有可用的GPU,如果没有GPU,则返回[cpu(),]。"""
    devices = [torch.device(f'cuda:{i}')for i in range(torch.cuda.device_count())]
    return devices if devices else [torch.device('cpu')]

try_gpu(),try_gpu(10),try_all_gpus()

(device(type='cuda', index=0),
 device(type='cpu'),
 [device(type='cuda', index=0)])

In [ ]:
#模型转换至GPU上进行运算：需要转换的对象：模型，数据,损失函数
if torch.cuda.is_available():
    net = net.cuda()
    lossFun = lossFun.cuda()
    data = data.cuda()
    label = label.cuda()

In [10]:
x = torch.ones(2,3,device=try_gpu())
x
# z = x.cuda(i) 不同gpu

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

 神经网络与GPU

In [11]:
net = nn.Sequential(nn.Linear(3,1))
net = net.to(device=try_gpu()) #拷贝

net(x) #传输数据 2x3 mm 3x1 = 2x1

tensor([[-0.6568],
        [-0.6568]], device='cuda:0', grad_fn=<AddmmBackward0>)

In [12]:
net[0].weight.data

tensor([[-0.1327,  0.0144, -0.3419]], device='cuda:0')