# 小结

• 标量、向量、矩阵和张量是线性代数中的基本数学对象。    
• 向量泛化⾃标量，矩阵泛化⾃向量。    
• 标量、向量、矩阵和张量分别具有零、⼀、⼆和任意数量的轴。      
• ⼀个张量可以通过sum和mean沿指定的轴降低维度。    
• 两个矩阵的按元素乘法被称为他们的Hadamard积(点积)。它与矩阵乘法不同。   
• 在深度学习中，我们经常使⽤范数，如L1范数、L2范数和Frobenius范数。    
• 我们可以对标量、向量、矩阵和张量执⾏各种操作。

# 练习

1. 证明⼀个矩阵A的转置的转置是A，即(A⊤)⊤ = A。
2. 给出两个矩阵A和B，证明“它们转置的和”等于“它们和的转置”，即A⊤ + B⊤ = (A + B)⊤。
3. 给定任意⽅阵A，A + A⊤总是对称的吗?为什么?
4. 我们在本节中定义了形状(2, 3, 4)的张量X。len(X)的输出结果是什么？
5. 对于任意形状的张量X,len(X)是否总是对应于X特定轴的⻓度?这个轴是什么?
6. 运⾏A/A.sum(axis=1)，看看会发⽣什么。你能分析原因吗？
7. 考虑⼀个具有形状(2, 3, 4)的张量，在轴0、1、2上的求和输出是什么形状?
8. 为linalg.norm函数提供3个或更多轴的张量，并观察其输出。对于任意形状的张量这个函数计算得到什么?

1.
对于A中的一个元素aij，其在第 i 行第 j 列，转置后出现在第 j 行第 i 列，再转置一次就出现在第 i 行第 j 列，又回到了原来的位置。所以，一个矩阵转置的转置还是它自己。

2.
假设 A 第 i 行第 j 列的元素是 aij，B 第 i 行第 j 列的元素是 bij，两者均在。对于 AT + BT，其第 j 行第 i 列的值为 aij + bij；对于 (A + B)T，其第 j 行第 i 列的值也为 aij + bij，推广至即可知 AT + BT = (A + B)T。

3.
是，因为 (A + AT)T = AT + (AT)T = A + AT。

In [1]:
#4,5
import torch
X = torch.arange(24).reshape(2, 3, 4)
len(X)
#总输出0轴维度

2

In [6]:
#6
A/A.sum(axis=1)
#发生运行时错误，原因是 A 是一个 5 * 4 的矩阵，而 A.sum(axis=1) 是一个大小为 5 的向量，两者不能相除。   
#（注：广播机制只能发生在两者维数相同的情况下）

RuntimeError: The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 1

In [8]:
#6修改
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
sum_A = A.sum(axis=1, keepdims=True)#指定轴降维变成1->（5,1）,默认False则是直接去掉
A,sum_A,A/sum_A,A.sum(axis=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 6.],
         [22.],
         [38.],
         [54.],
         [70.]]),
 tensor([[0.0000, 0.1667, 0.3333, 0.5000],
         [0.1818, 0.2273, 0.2727, 0.3182],
         [0.2105, 0.2368, 0.2632, 0.2895],
         [0.2222, 0.2407, 0.2593, 0.2778],
         [0.2286, 0.2429, 0.2571, 0.2714]]),
 tensor([ 6., 22., 38., 54., 70.]))

In [11]:
#7
X,X.sum(axis=0),X.sum(axis=1),X.sum(axis=2)
#在轴 0 上求和，形状为 [3 * 4]
#在轴 1 上求和，形状为 [2 * 4]
#在轴 2 上求和，形状为 [2 * 3]
#相当于对哪个轴求和，就是降维去掉哪个轴。

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]),
 tensor([[12, 15, 18, 21],
         [48, 51, 54, 57]]),
 tensor([[ 6, 22, 38],
         [54, 70, 86]]))

In [21]:
#8
#计算得到张量中所有值的 L2范数-Frobenius范数（Frobenius norm）是矩阵元素平⽅和的平⽅根
#linalg.norm 其实是 numpy 的一个模块，功能是求各种范式，默认为L2范数=torch.norm
import numpy as np
Y=np.ones((2,5,10))
np.linalg.norm(Y),torch.norm(torch.ones((2,5,10)))

(10.0, tensor(10.))