# 小结

深度学习存储和操作数据的主要接口是张量（n n维数组）。它提供了各种功能，包括基本数学运算、⼴     
播、索引、切⽚、内存节省和转换其他Python对象。

# 练习

1. 运⾏本节中的代码。将本节中的条件语句X == Y更改为X < Y或X > Y，然后看看你可以得到什么样的张量。
2. ⽤其他形状（例如三维张量）替换⼴播机制中按元素操作的两个张量。结果是否与预期相同？

In [4]:
#1二维连结
import torch
X = torch.arange(12, dtype=torch.float32).reshape((3,4))#注意向量形式默认为列向量
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1),X == Y,X < Y
#二维：行0，列1;三维：行0，行1，列2;由里到外(size要保证拓展后为完整矩阵！)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]),
 tensor([[False,  True, False,  True],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[ True, False,  True, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [5]:
#1三维连结
X = torch.arange(12, dtype=torch.float32).reshape((3,2,2))
Y = torch.tensor([[[2,1], [1,2]], [[4,3],[1,0]],[[1,3],[2,0]]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1),torch.cat((X, Y), dim=2)

(tensor([[[ 0.,  1.],
          [ 2.,  3.]],
 
         [[ 4.,  5.],
          [ 6.,  7.]],
 
         [[ 8.,  9.],
          [10., 11.]],
 
         [[ 2.,  1.],
          [ 1.,  2.]],
 
         [[ 4.,  3.],
          [ 1.,  0.]],
 
         [[ 1.,  3.],
          [ 2.,  0.]]]),
 tensor([[[ 0.,  1.],
          [ 2.,  3.],
          [ 2.,  1.],
          [ 1.,  2.]],
 
         [[ 4.,  5.],
          [ 6.,  7.],
          [ 4.,  3.],
          [ 1.,  0.]],
 
         [[ 8.,  9.],
          [10., 11.],
          [ 1.,  3.],
          [ 2.,  0.]]]),
 tensor([[[ 0.,  1.,  2.,  1.],
          [ 2.,  3.,  1.,  2.]],
 
         [[ 4.,  5.,  4.,  3.],
          [ 6.,  7.,  1.,  0.]],
 
         [[ 8.,  9.,  1.,  3.],
          [10., 11.,  2.,  0.]]]))

In [7]:
#2二维广播
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b, a+b
#由于a和b分别是3 × 1和1 × 2矩阵，如果让它们相加，它们的形状不匹配。
#我们将两个矩阵⼴播为⼀个更⼤的3 × 2矩阵，如下所⽰：矩阵a将复制列，矩阵b将复制⾏，然后再按元素相加

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]),
 tensor([[0, 1],
         [1, 2],
         [2, 3]]))

In [8]:
#2三维广播
a = torch.arange(3).reshape(3, 1, 1)
b = torch.arange(2).reshape(1, 2, 1)
a, b, a+b

(tensor([[[0]],
 
         [[1]],
 
         [[2]]]),
 tensor([[[0],
          [1]]]),
 tensor([[[0],
          [1]],
 
         [[1],
          [2]],
 
         [[2],
          [3]]]))